import test from 'node:test';
import assert from 'node:assert/strict';
import {parseOwnedRule} from '../lib/model.mjs';
test('owned search comparison accepts whole copy thresholds and rejects invalid input',()=>{assert.deepEqual(parseOwnedRule(' owned > 3 '),{ownedAbove:3});assert.deepEqual(parseOwnedRule('OWNED>0'),{ownedAbove:0});for(const query of ['owned > -1','owned > 3.5','owned > 9007199254740992','owned card','fire > 10'])assert.equal(parseOwnedRule(query),null);});
import {normalize,priceOf,validateDraft,validateCover,DISPLAY_TYPES,signature,exportDeck,reconcile,allocate} from '../lib/model.mjs';
const sets=[{id:'Tetramon',suffix:'',expansion:0,monsterOrder:[1]},{id:'Ascension',suffix:'Ascension',expansion:7,monsterOrder:[1]},{id:'Ghost',suffix:'Ghost',expansion:2,isDestiny:false,monsterOrder:[1]},{id:'GhostBlack',suffix:'GhostBlack',expansion:2,isDestiny:true,monsterOrder:[1]}];
const cards=[{id:'Tetramon:0',setId:'Tetramon',baseId:'1',monsterId:1,expansion:0,saveIndex:0,name:'Pigni'},{id:'Tetramon:6',setId:'Tetramon',baseId:'1',monsterId:1,expansion:0,saveIndex:6,name:'Pigni'},{id:'Ascension:0',setId:'Ascension',baseId:'1',monsterId:1,expansion:7,saveIndex:0,name:'Pigni'}, {id:'Ghost:1',setId:'Ghost',baseId:'1',monsterId:1,expansion:2,isDestiny:false,saveIndex:1,name:'Pigni'}, {id:'GhostBlack:1',setId:'GhostBlack',baseId:'1',monsterId:1,expansion:2,isDestiny:true,saveIndex:1,name:'Pigni'}];
test('inventory adds deck and storage copies once, not to build availability',()=>{
 const s={m_CardCollectedList:[3],m_GenCardMarketPriceList:[{generatedMarketPrice:10,pricePercentChangeList:20,pastPricePercentChangeList:[0,10,20]}],m_DeckCompactCardDataList:[{deckName:'Deck',compactCardDataAmountList:[{expansionType:0,cardSaveIndex:0,amount:2}]}],m_CardStorageShelfSaveDataList:[{compactCardDataAmountList:[{expansionType:0,cardSaveIndex:0,amount:4}]}],m_CardShelfSaveDataList:[{cardDataList:[{expansionType:0,monsterType:1,borderType:0,isFoil:false,cardGrade:0}]}]};
 const n=normalize(s,{sets,cards}),c=n.cards[0];assert.equal(c.owned,10);assert.equal(c.available,3);assert.equal(c.inDeck,2);assert.equal(c.elsewhere,5);assert.equal(c.value,120);assert.deepEqual(c.history,[10,11,12]);assert.equal(s.m_CardCollectedList[0],3);
});
test('ghost white and black map to separate inventories and prices',()=>{const s={m_CardCollectedList:[],m_CardCollectedListGhost:[0,2],m_CardCollectedListGhostBlack:[0,3],m_GenCardMarketPriceListGhost:[0,{generatedMarketPrice:100,pricePercentChangeList:0}],m_GenCardMarketPriceListGhostBlack:[0,{generatedMarketPrice:200,pricePercentChangeList:0}],m_DeckCompactCardDataList:[{compactCardDataAmountList:[{expansionType:2,isDestiny:true,cardSaveIndex:1,amount:1}]}]};const n=normalize(s,{sets,cards});assert.equal(n.cards[3].owned,2);assert.equal(n.cards[4].owned,4);assert.equal(n.cards[3].price,100);assert.equal(n.cards[4].price,200);});
test('graded compact amount is the grade, not a quantity',()=>{const n=normalize({m_CardCollectedList:[1],m_GradedCardInventoryList:[{expansionType:0,cardSaveIndex:0,gradedCardIndex:6,amount:10}],m_CardShelfSaveDataList:[{cardDataList:[{expansionType:0,monsterType:1,borderType:0,cardGrade:10}]}]},{sets,cards});assert.equal(n.cards[0].owned,3);assert.equal(n.cards[0].available,1);assert.equal(n.graded.reduce((n,c)=>n+c.amount,0),2);assert.equal(n.graded[1].grade,10);});
test('unclaimed opener cards, donation box and combination shelves remain owned but unavailable',()=>{const entry={expansionType:0,cardSaveIndex:0,amount:3};const n=normalize({m_CardCollectedList:[1],m_AutoPackOpenerSaveDataList:[{compactCardDataAmountList:[entry]}],m_BulkDonationSaveDataList:[{compactCardDataAmountList:[entry]}],m_CardItemCombiShelfSaveDataList:[{cardDataList:[{expansionType:0,monsterType:1,borderType:0}]}]},{sets,cards});assert.equal(n.cards[0].owned,8);assert.equal(n.cards[0].available,1);});
test('four-copy rule spans cosmetic variants and expansions',()=>{assert.throws(()=>validateDraft({name:'test',entries:[{cardId:'Tetramon:0',amount:2},{cardId:'Tetramon:6',amount:2},{cardId:'Ascension:0',amount:1}]},cards),/four copies/);assert.doesNotThrow(()=>validateDraft({name:'test',entries:[{cardId:'Tetramon:0',amount:2},{cardId:'Ascension:0',amount:2}]},cards));});
test('rejects invalid amounts, unknown cards and oversized decks',()=>{for(const amount of [-1,0,1.5,5])assert.throws(()=>validateDraft({name:'a',entries:[{cardId:'Tetramon:0',amount}]},cards));assert.throws(()=>validateDraft({name:'a',entries:[{cardId:'unknown',amount:1}]},cards));const cs=Array.from({length:13},(_,i)=>({id:String(i),baseId:String(i)}));assert.throws(()=>validateDraft({name:'a',entries:cs.map(c=>({cardId:c.id,amount:4}))},cs),/50/);});
test('allocation chooses cheapest available copies and reports unmet copies as draft choices',()=>{const cs=cards.slice(0,3).map((c,i)=>({...c,available:[1,4,2][i],price:[2,10,1][i]}));assert.deepEqual(allocate(cs,'1',4,'Tetramon'),[{cardId:'Ascension:0',amount:2},{cardId:'Tetramon:0',amount:1},{cardId:'Tetramon:6',amount:1}]);});
test('export uses installed game text grammar and one-based indexes',()=>{const text=exportDeck({entries:[{cardId:'Tetramon:0',amount:3},{cardId:'Ghost:1',amount:1}]},cards);assert.equal(text,'3X Pigni Tetramon N 001\n1X Pigni Ghost N 002');const parsed=text.split('\n').map(line=>{const [qty,name,expansion,back,index]=line.split(' ');return {amount:Number(qty.replace('X','')),name,expansion,isDestiny:back!=='N',saveIndex:Number(index)-1};});assert.equal(parsed[1].saveIndex,1);assert.equal(parsed[1].isDestiny,false);});
test('exported draft becomes in-game only after matching sync, and reverts when removed',()=>{const draft={id:'local',name:'Draft name',entries:[{cardId:'Tetramon:0',amount:4}],exportedAt:'now'};const game={id:'game-0',name:'Different name',entries:[{cardId:'Tetramon:0',amount:2},{cardId:'Tetramon:0',amount:2}]};assert.equal(reconcile([draft],[])[0].status,'exported');const linked=reconcile([draft],[game])[0];assert.equal(linked.status,'in-game');assert.equal(reconcile([linked],[])[0].status,'draft');assert.equal(signature(draft.entries),signature(game.entries));});
test('matching requires exact variants and does not link two drafts to one game deck',()=>{const d={id:'a',entries:[{cardId:'Tetramon:0',amount:1}]};assert.equal(reconcile([d],[{id:'g',entries:[{cardId:'Tetramon:6',amount:1}]}])[0].status,'draft');assert.deepEqual(reconcile([d,{...d,id:'b'}],[{id:'g',entries:d.entries}]).map(d=>d.status),['in-game','draft']);});
test('market prices use percent adjustment, not raw generated price',()=>{assert.equal(priceOf({generatedMarketPrice:20,pricePercentChangeList:-25}),15);});

test('graded values use grade bonuses and prize metadata is not double counted',()=>{const card={expansionType:0,monsterType:1,borderType:0,cardGrade:10};const n=normalize({m_CardCollectedList:[2],m_GenCardMarketPriceList:[{generatedMarketPrice:100,pricePercentChangeList:20,pastPricePercentChangeList:[0]}],m_GenGradedCardPriceMultiplierList:Array(10).fill(2),m_CardItemCombiShelfSaveDataList:[{objectType:55,cardDataList:[card]}],m_CardShelfSaveDataList:[{objectType:44,cardDataList:[{...card,cardGrade:0}]}],m_TournamentData:{m_PrizeDataList:[card]}},{sets,cards});const c=n.cards[0];assert.equal(c.owned,4);assert.equal(c.available,2);assert.equal(c.gradedCount,1);assert.equal(c.gradePrices[9].price,264);assert.equal(c.gradePrices[9].history[0],224);assert.equal(c.value,624);assert.equal(c.locations.Projectors,1);assert.equal(c.grades[0].location,'Tournament prize shelves');});


test('all display furniture types reconcile even when absent from the real save',()=>{
 for(const [type,name] of Object.entries(DISPLAY_TYPES)){
  const card={expansionType:0,monsterType:1,borderType:0,cardGrade:0};
  const n=normalize({m_CardCollectedList:[2],m_CardShelfSaveDataList:[{objectType:Number(type),isBoxed:true,cardDataList:[card]}],m_CardItemCombiShelfSaveDataList:[{objectType:Number(type),cardDataList:[{...card,cardGrade:9}]}]},{sets,cards});
  assert.equal(n.cards[0].owned,4,name);assert.equal(n.cards[0].available,2,name);assert.equal(n.cards[0].locations[name],1,name);assert.equal(n.cards[0].gradedCount,1,name);
  const coverage=n.displayCoverage.find(x=>x.type===Number(type));assert.equal(coverage.fixtures,2);assert.equal(coverage.copies,2);
 }
 const empty=normalize({m_CardCollectedList:[]},{sets,cards});assert.equal(empty.displayCoverage.length,Object.keys(DISPLAY_TYPES).length);assert.ok(empty.displayCoverage.every(x=>x.fixtures===0&&x.copies===0));
});
test('unknown future display types still contribute inventory',()=>{const n=normalize({m_CardCollectedList:[],m_CardShelfSaveDataList:[{objectType:999,cardDataList:[{expansionType:0,monsterType:1,borderType:0}]}]},{sets,cards});assert.equal(n.cards[0].owned,1);assert.equal(n.cards[0].locations['Other card display (type 999)'],1);});
test('deck cover choices preserve order, require deck membership and cap at three',()=>{
 const entries=[{cardId:'Tetramon:0',amount:1},{cardId:'Tetramon:6',amount:1}];assert.deepEqual(validateCover(['Tetramon:6','Tetramon:0'],entries),['Tetramon:6','Tetramon:0']);
 assert.throws(()=>validateCover(['Ascension:0'],entries));assert.throws(()=>validateCover(['Tetramon:0','Tetramon:0'],entries));assert.throws(()=>validateCover(['a','b','c','d'],entries));
 assert.deepEqual(validateDraft({name:'Cover',entries,coverCardIds:['Tetramon:6']},cards).coverCardIds,['Tetramon:6']);
});
import {gradeDistribution,estimateGrading,editionOf,matchesFacets,strongestStat,compareCardNumber} from '../lib/model.mjs';
test('grading probabilities and regrade boundary aggregation match game branches',()=>{const fresh=gradeDistribution();assert.ok(Math.abs(fresh.reduce((n,o)=>n+o.probability,0)-1)<1e-12);assert.equal(fresh[9].probability,.384);assert.deepEqual(gradeDistribution(5),[{grade:4,probability:.29},{grade:5,probability:.41},{grade:6,probability:.3}]);assert.ok(Math.abs(gradeDistribution(1)[0].probability-.7)<1e-12);assert.ok(Math.abs(gradeDistribution(10)[1].probability-.71)<1e-12);});
test('expected grading value deducts service and allocated delivery, regrade may lose value',()=>{const c={price:50,gradePrices:Array.from({length:10},(_,i)=>({price:(i+1)*100}))};const e=estimateGrading(c,0,0,8);assert.equal(e.fee,11.25);assert.ok(Math.abs(e.expected-853.1)<1e-8);assert.equal(e.gain,e.expected-11.25-50);const r=estimateGrading(c,10,0,1);assert.equal(r.expected,971);assert.equal(r.gain,-49);assert.equal(estimateGrading({price:5,gradePrices:[]}),null);});
test('facet OR within a category and AND between edition and foil',()=>{const c={expansion:0,border:5,foil:true,setId:'Tetramon',rarity:'Rare',elementIndex:2};assert.equal(editionOf(c),'Full Art');assert.ok(matchesFacets(c,{sets:['Destiny','Tetramon'],editions:['Full Art'],foils:['Foil']}));assert.equal(matchesFacets({...c,foil:false},{editions:['Full Art'],foils:['Foil']}),false);assert.equal(strongestStat({stats:{fire:1,earth:18}}),18);assert.ok(compareCardNumber({cardNumber:1},{cardNumber:2})<0);});
test('display analytics exclude sale shelves and storage while collection retains them',()=>{const physical={expansionType:0,monsterType:1,borderType:0};const n=normalize({m_CardCollectedList:[],m_CardShelfSaveDataList:[{objectType:10,cardDataList:[physical]},{objectType:44,cardDataList:[physical]}],m_CardStorageShelfSaveDataList:[{compactCardDataAmountList:[{expansionType:0,cardSaveIndex:0,amount:2}]}]},{sets,cards});assert.equal(n.cards[0].owned,4);assert.equal(n.displayHoldings.length,1);assert.equal(n.displayHoldings[0].location,'Projectors');});


import {groupCardIdentities,representativeCard,matchesStatRules,parseStatRule} from '../lib/model.mjs';
test('equivalent edition slots select exactly one Ascension edition per finish',()=>{const editions=['Base','First Edition','Silver','Gold','EX','Full Art'];for(const [border,name] of editions.entries()){for(const foil of [false,true]){const all=Array.from({length:12},(_,i)=>({expansion:7,border:i%6,foil:i>=6}));const matches=all.filter(c=>matchesFacets(c,{editions:[name],foils:[foil?'Foil':'Non-foil']}));assert.equal(matches.length,1);assert.equal(matches[0].border,border);assert.equal(matches[0].foil,foil);}}assert.equal(editionOf({expansion:7,border:3}),'Gold');});
test('browser groups a card across sets and retains total available copies with preferred art',()=>{const cs=[{baseId:'1',id:'t',setId:'Tetramon',border:5,foil:false,available:2,owned:3},{baseId:'1',id:'a',setId:'Ascension',border:5,foil:false,available:4,owned:5},{baseId:'2',id:'b',setId:'Tetramon',border:0,foil:false,available:1,owned:1}];const gs=groupCardIdentities(cs,'Ascension');assert.equal(gs.length,2);assert.equal(gs[0].id,'a');assert.equal(gs[0].available,6);assert.equal(gs[0].owned,8);assert.equal(representativeCard(cs.filter(c=>c.baseId==='2'),'Ghost').id,'b');assert.equal(cs[1].owned,5);});
test('stat comparisons parse search suggestions and combine across elements',()=>{assert.deepEqual(parseStatRule('water >= 12'),{element:'Water',operator:'>=',value:12});assert.equal(parseStatRule('fire dragon'),null);const c={stats:{FireElement:8,WaterElement:12}};assert.equal(matchesStatRules(c,[parseStatRule('fire < 9'),parseStatRule('water >= 12')]),true);assert.equal(matchesStatRules(c,[parseStatRule('fire > 8')]),false);assert.equal(matchesStatRules(c,[parseStatRule('earth = 0')]),false);});
import {observedDuelWins} from '../lib/model.mjs';
test('observed duel wins do not invent daily totals across gaps or counter resets',()=>{assert.deepEqual(observedDuelWins([{day:1,duelWins:12}]),[]);const rows=observedDuelWins([{day:1},{day:1,duelWins:12},{day:1,duelWins:13},{day:1,duelWins:15},{day:3,duelWins:19},{day:4,duelWins:0}]);assert.deepEqual(rows,[{label:'Day 1',wins:3,multipleDays:false,reset:false},{label:'Days 1–3',wins:4,multipleDays:true,reset:false},{label:'Days 3–4',wins:null,multipleDays:true,reset:true}]);});
import {EFFECT_KEYWORDS,hasEffectKeyword,compareCards,gradingStock} from '../lib/model.mjs';
test('effect keywords match inflections and OR together while respecting other facets',()=>{const c={description:'Your opponent draws 2 cards. Discard a card.',elementIndex:1};assert.ok(hasEffectKeyword(c,'Draw'));assert.ok(hasEffectKeyword(c,'Discard'));assert.equal(hasEffectKeyword(c,'Boost'),false);assert.ok(matchesFacets(c,{keywords:['Boost','Discard'],elements:['1']}));assert.equal(matchesFacets(c,{keywords:['Draw'],elements:['2']}),false);assert.ok(hasEffectKeyword({description:'This card is frozen.'},'Freeze'));assert.ok(Object.keys(EFFECT_KEYWORDS).length>4);});
test('each sort supports both directions without changing the sort field',()=>{const a={cardNumber:1,baseId:'1',name:'Alpha',value:30,price:3,owned:10,stats:{FireElement:5},gradingEstimate:{gain:2}},b={cardNumber:2,baseId:'2',name:'Beta',value:60,price:6,owned:20,stats:{FireElement:9},gradingEstimate:{gain:4}};for(const key of ['number','name','value','price','gradeGain','owned','strongest']){assert.ok(compareCards(a,b,key,'asc')<0,key);assert.ok(compareCards(a,b,key,'desc')>0,key);}});
test('grading eligibility includes displays without double counting and never invents unowned grades',()=>{const c={id:'x',available:0,ungradedOwned:1,grades:[{grade:9,location:'Projectors'},{grade:9,location:'Graded inventory'}]},display=[{cardId:'x',grade:0,amount:1},{cardId:'x',grade:9,amount:1}];assert.deepEqual(gradingStock(c,0,display),{owned:1,inventory:0,onDisplay:1,eligible:1});assert.equal(gradingStock(c,0,display,'duplicates').eligible,0);assert.deepEqual(gradingStock(c,9,display),{owned:2,inventory:1,onDisplay:1,eligible:2});assert.equal(gradingStock(c,9,display,'duplicates').eligible,1);assert.equal(gradingStock(c,10,display).eligible,0);});
import {completionSatisfied,collectionConditionRows} from '../lib/model.mjs';
const conditionFixture=()=>({id:'t:0',name:'Test',price:10,ungradedOwned:2,available:1,owned:5,gradedCount:3,value:620,grades:[{grade:9,price:100,location:'Graded inventory'},{grade:9,price:100,location:'Projectors'},{grade:10,price:400,location:'Projectors'}],gradePrices:Array.from({length:10},(_,i)=>({grade:i+1,price:i===9?400:100}))});
test('condition rows split counts and values without losing or double counting holdings',()=>{const c=conditionFixture(),rows=collectionConditionRows([c]);assert.deepEqual(rows.map(r=>[r.displayGrade,r.owned,r.value]),[[0,2,20],[9,2,200],[10,1,400]]);assert.equal(rows.reduce((n,r)=>n+r.owned,0),c.owned);assert.equal(rows.reduce((n,r)=>n+r.value,0),c.value);assert.equal(rows[0].gradedCount,0);assert.equal(c.owned,5);});
test('graded-only ownership satisfies any-copy completion but not ungraded completion',()=>{const c={...conditionFixture(),ungradedOwned:0,available:0,owned:3};const any=collectionConditionRows([c],'any')[0],raw=collectionConditionRows([c],'ungraded')[0];assert.equal(any.owned,0);assert.equal(any.value,0);assert.equal(any.gradedVersionOwned,true);assert.equal(any.rowMissing,false);assert.equal(raw.rowMissing,true);assert.equal(raw.gradedVersionOwned,false);});
test('PSA targets add one missing target row, and higher grades satisfy thresholds',()=>{const c=conditionFixture();assert.ok(completionSatisfied(c,'psa-9'));assert.ok(completionSatisfied(c,'psa-10'));const lower={...c,grades:c.grades.filter(g=>g.grade===9),gradedCount:2,owned:4};assert.equal(completionSatisfied(lower,'psa-10'),false);const rows=collectionConditionRows([lower],'psa-10');assert.equal(rows.filter(r=>r.rowMissing).length,1);assert.equal(rows.at(-1).displayGrade,10);assert.equal(rows.at(-1).owned,0);assert.equal(rows.at(-1).value,0);assert.equal(collectionConditionRows([c],'psa-8').filter(r=>r.isTargetPlaceholder).length,0);});
test('an entirely unowned variant is missing once, not ten times, for each target',()=>{const c={...conditionFixture(),owned:0,ungradedOwned:0,available:0,grades:[],gradedCount:0};for(const mode of ['any','ungraded','psa-8','psa-10']){const rows=collectionConditionRows([c],mode);assert.equal(rows.filter(r=>r.rowMissing).length,1,mode);assert.equal(rows.reduce((n,r)=>n+r.owned,0),0);}});

import {validateRecord,evolutionIds,missingEvolutions,usableCopies,draftIssues} from '../lib/model.mjs';
test('manual records validate whole nonnegative counts and survive exact-match reconciliation',()=>{
 assert.deepEqual(validateRecord(),{wins:0,losses:0});for(const record of [{wins:-1,losses:0},{wins:1.5,losses:0},{wins:0,losses:Infinity}])assert.throws(()=>validateRecord(record));
 const d={id:'local',entries:[{cardId:'a',amount:1}],record:{wins:8,losses:3}},game={id:'g',name:'Renamed',entries:d.entries};const linked=reconcile([d],[game])[0];assert.deepEqual(linked.record,d.record);assert.equal(linked.status,'in-game');const detached=reconcile([linked],[{...game,entries:[{cardId:'b',amount:1}]}])[0];assert.equal(detached.status,'draft');assert.deepEqual(detached.record,d.record);assert.match(detached.detachedReason,/no longer matches/);assert.equal(reconcile([detached],[game])[0].status,'in-game');
});
test('evolution navigation spans ancestors and descendants while warnings require immediate lower stage',()=>{
 const cs=[{id:'a',baseId:'1',name:'Basic',previousEvolution:0},{id:'b',baseId:'2',name:'Middle',previousEvolution:1,previousName:'Basic'},{id:'c',baseId:'3',name:'Final',previousEvolution:2,previousName:'Middle'},{id:'d',baseId:'4',previousEvolution:0}];
 assert.deepEqual([...evolutionIds(cs,['2'])].sort(),['1','2','3']);assert.equal(missingEvolutions({entries:[{cardId:'c',amount:1}]},cs)[0].parentId,'2');assert.equal(missingEvolutions({entries:[{cardId:'b',amount:1},{cardId:'c',amount:1}]},cs).length,1);
});
test('replacement credit uses an exact build, never a reused game slot; draft overlap stays advisory',()=>{
 const card={id:'a',available:1},game={id:'game-0',entries:[{cardId:'a',amount:3}]},d={id:'d',entries:[{cardId:'a',amount:4}],replacementSignature:signature(game.entries)};
 assert.equal(usableCopies(card,d,[game]),4);assert.equal(usableCopies(card,d,[{...game,entries:[{cardId:'b',amount:3}]}]),1);
 const other={id:'other',name:'Other build',status:'draft',entries:[{cardId:'a',amount:1}]};const issue=draftIssues(d,[card],[game],[d,other])[0];assert.equal(issue.short,0);assert.equal(issue.shared,true);assert.equal(d.entries[0].amount,4);
});
test('automatic variants select quantity or price only among usable copies',()=>{
 const cs=[{id:'a',baseId:'1',available:2,price:8,expansion:0},{id:'b',baseId:'1',available:8,price:2,expansion:0},{id:'c',baseId:'1',available:0,price:100,expansion:0}];assert.equal(allocate(cs,'1',1,null,'quantity')[0].cardId,'b');assert.equal(allocate(cs,'1',1,null,'expensive')[0].cardId,'a');
});
test('cards in grading and staged grading submissions remain owned but not available',()=>{
 const physical={expansionType:0,monsterType:1,borderType:0,cardGrade:0};const n=normalize({m_CardCollectedList:[0],m_GradeCardInProgressList:[{m_CardDataList:[physical]}],m_CurrentGradeCardSubmitSet:{m_CardDataList:[physical]}},{sets,cards});assert.equal(n.cards[0].owned,2);assert.equal(n.cards[0].available,0);assert.equal(n.cards[0].locations['At grading'],1);assert.equal(n.cards[0].locations['Grading submission'],1);
});

test('owned Ghost variants participate in explicit deck allocation strategies',()=>{const cs=[{id:'base',baseId:'1',available:5,price:2,expansion:0},{id:'ghost',baseId:'1',available:1,price:2000,expansion:2}];assert.equal(allocate(cs,'1',1,null,'expensive')[0].cardId,'ghost');assert.equal(allocate(cs,'1',1,null,'quantity')[0].cardId,'base');});

import {completionProgress,completionGrades,deckSyncState} from '../lib/model.mjs';
test('completion requires every selected condition and missing rows match progress without duplicating value',()=>{
 const c=conditionFixture();assert.deepEqual(completionGrades('conditions:0,8,10'),[0,8,10]);
 assert.equal(completionSatisfied(c,'conditions:0,8'),false);assert.equal(completionSatisfied(c,'conditions:0,9,10'),true);
 for(const mode of ['conditions:1,8','conditions:0,8','conditions:8,9','conditions:0,9,10']){const rows=collectionConditionRows([c],mode),progress=completionProgress([c],mode);assert.equal(rows.filter(r=>r.rowMissing).length,progress.missing);assert.equal(rows.reduce((n,r)=>n+r.value,0),c.value);assert.equal(new Set(rows.map(r=>r.rowKey)).size,rows.length);}
 const empty={...c,owned:0,ungradedOwned:0,grades:[],gradedCount:0};assert.equal(collectionConditionRows([empty],'conditions:0,8,10').filter(r=>r.rowMissing).length,3);
 assert.deepEqual(completionProgress([c],'conditions:0,8,9,10'),{owned:3,total:4,missing:1,percent:75});
});
test('editing a live build has a pending-update identity and credits its original copies',()=>{
 const original={id:'g',name:'Original',entries:[{cardId:'a',amount:4}]},d={entries:[{cardId:'a',amount:3},{cardId:'b',amount:1}],replacementSignature:signature(original.entries),replacementName:'Original'};
 assert.deepEqual(deckSyncState(d,[original]),{pending:true,originalExists:true,name:'Original'});assert.equal(draftIssues(d,[{id:'a',available:0},{id:'b',available:1}],[original],[]).some(x=>x.short),false);
 assert.equal(deckSyncState(d,[{...original,entries:d.entries}]).originalExists,false);assert.equal(deckSyncState({...d,entries:original.entries},[original]),null);assert.equal(deckSyncState({entries:d.entries},[]),null);
});
